site_title = "MyArXiv"
limit_days = 7
cache_url = "https://nukeinc.github.io/arxiv_daily/cache.json"

[[sources]]
limit = 150
category = "nucl-th"
title = "Nuclear Theory"

[[sources]]
limit = 150
category = "nucl-ex"
title = "Nuclear Experiment"

[[sources]]
limit = 150
category = "hep-ph"
title = "High Energy Phenomenology"

[[sources]]
limit = 150
category = "hep-th"
title = "High Energy Theory"

[[sources]]
limit = 150
category = "cond-mat.mtrl-sci"
title = "Materials Science"

[[sources]]
limit = 150
category = "cond-mat.str-el"
title = "Strongly Correlated Electrons"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
